# Use root/example as user/password credentials
version: '3.1'

services:
  pg-db:
    image: postgres
    volumes:
      - "postgres:/data/postgres"
    env_file:
      - .env
    ports:
      - 5433:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    depends_on:
      - pg-db
volumes:
  postgres:

networks:
  frontend:
  backend: